cc_library(
    name = "SearchingAlgorithms",
    srcs = ["LinearSearch.cpp", "HashMap_Example.cpp"],
    hdrs = ["Searching.h"],
    deps = ["//src/TestData:TestData",],
    visibility = ["//src:__pkg__"],
)