cc_library(
    name = "SearchingAlgorithms",
    srcs = [
        "BinarySearch.cpp",
        "LinearSearch.cpp", 
        "HashMap_Example.cpp"
    ],
    hdrs = ["Searching.h"],
    deps = ["//src/TestData:TestData",],
    visibility = ["//src:__pkg__",
                  "//src/Benchmarking:__pkg__"],
)