cc_library(
    name = "Benchmark",
    srcs = ["Benchmarking.cpp"],
    hdrs = ["Benchmark.h"],
    deps = ["//src/SearchingAlgorithms:SearchingAlgorithms",
            "//src/SortingAlgorithms:SortingAlgorithms",
            "//src/TestData:TestData"],
    visibility = ["//src:__pkg__",
                  "//src/Practice:__pkg__"],
)