cc_library(
    name = "Benchmark",
    srcs = ["Benchmarking.cpp"],
    hdrs = ["Benchmark.h"],
    deps = ["//src/SortingAlgorithms:SortingAlgorithms",
            "//src/TestData:TestData"],
    visibility = ["//src:__pkg__"],
)