cc_library(
    name = "SortingAlgorithms",
    srcs = ["BubbleSort.cpp", "InsertionSort.cpp", "SelectionSort.cpp", "MergeSort.cpp"],
    hdrs = ["Sorting.h"],
    visibility = ["//src:__pkg__"],
)