cc_library(
    name = "SortingAlgorithms",
    srcs = [
        "BubbleSort.cpp", 
        "InsertionSort.cpp", 
        "SelectionSort.cpp", 
        "MergeSort.cpp", 
        "QuickSort.cpp",
        "HeapSort.cpp",
        "TimSort.cpp"
    ],
    hdrs = ["Sorting.h"],
    visibility = ["//src:__pkg__"],
)