cc_library(
    name = "Practice",
    srcs = ["practice.cpp",
            "practiceSorts.cpp"],
    hdrs = ["practice.h"],
    deps = ["//src/Benchmarking:Benchmark",
            "//src/TestData:TestData"],
    visibility = ["//src:__pkg__"],
)