cc_library(
    name = "TestData",
    srcs = [
        "GenArrays.cpp", 
        "CheckData.cpp",
        "GenUsers.cpp"
        ],
    hdrs = [
        "TestData.h", 
        "GenUsers.h"
        ],
    visibility = ["//src:__pkg__", "//src/SearchingAlgorithms:__pkg__"],
)